### PR TITLE
Hatama console python

### PR DESCRIPTION
**Pull request by eraulo**
Taka issue: #77 
Console python tau iha  website tamba sira usa atu bele pratica karik sira seidauk instala python iha sira nia Komputador.
**Instrusaun**
1. git checkout 77_console_python
2. git pull
3. ./manage.py runserver
4. Ba home page no klik iha Console ita bele hare console python3.8

### CODE REVIEW

**Comment by eraulo** [comment]
> Hi @eraulo, hau atu review PR ida ne'e oinsa?
> Favor ida hakerek ho nia step para ita bele komprende.

**Comment by eraulo** [comment]
@marobo bele hare instrusaun iha leten.

**Comment by marobo** [comment]
hau hanoin python console nee ladun importante ita atu uza iha website karik,,,,  
karik hau tama tiha ona ba console nia laran oinsa hau ba vizita fali ba pajina sira seluk.?

**Comment by eraulo** [comment]
Se dehan console la importante, tamba sa mak ita tau dokumentus python iha ne'eba?
Tau console iha ne'eba karik sira le dokumentus no sira hakarak koko usa python.

**Pull request merged**
